### PR TITLE
Revamp create_vm_script to use configuration

### PR DESCRIPTION
**Pull request by djberg96**
This addresses an issue where there appears to be a race condition that results in static IP assignment failing when using provisioning from a pool if we use `New-SCVirtualMachine`. Instead, this approach is to create a configuration object, then apply the configuration.

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1463019

### CODE REVIEW

**Comment by djberg96** [comment]
BTW, the errors are unrelated and are the result of a change in the underlying logging classes.

**Comment by djberg96** [comment]
@miq-bot remove_label wip

**Comment by djberg96** [comment]
@miq-bot add_label fine/no

**Comment by blomquisg** [comment]
@jteehan tested this in https://github.com/ManageIQ/manageiq/pull/15610.  Merging based on his successful tests.

**Comment by simaishi** [comment]
Backported to Fine via https://github.com/ManageIQ/manageiq/pull/15610

**Pull request merged**
