### PR TITLE
Fix missing supports features for guest operations

### PR DESCRIPTION
**Pull request by agrare**
There were missing supports features for reboot and shutdown guest
operations.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1650506

### CODE REVIEW

**Comment by agrare** [comment]
@djberg96 PTAL

**Comment by agrare** [comment]
And of course these methods are actually implemented :)
https://github.com/ManageIQ/manageiq-providers-scvmm/blob/master/app/models/manageiq/providers/microsoft/infra_manager.rb#L123-L125
https://github.com/ManageIQ/manageiq-providers-scvmm/blob/master/app/models/manageiq/providers/microsoft/infra_manager.rb#L131-L134

**Comment by simaishi** [comment]
@agrare `hammer/yes`?

**Comment by agrare** [comment]
@simaishi done

**Pull request merged**
