### PR TITLE
Add support for storage fileshares

### PR DESCRIPTION
**Pull request by djberg96**
This adds `StorageFileShares` as a `storages` type for the SCVMM provider.

Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1454963

### CODE REVIEW

**Comment by djberg96** [comment]
@blomquisg Regarding get_inventory.ps1, it's the line endings. I stripped the Windows line endings. Dunno how they got back in there.

**Comment by djberg96** [comment]
@jteehan, Can you answer Greg's question regarding metrics support?

**Comment by jteehan** [comment]
I have no idea about the storage type support.  I would say no until we see what the answer actually is.

**Comment by djberg96** [comment]
@miq-bot add_label fine/yes

**Comment by bronaghs** [comment]
@djberg96 - Does this require a separate PR on the EUWE branch? Or can Satoe back port it?
Same goes for https://github.com/ManageIQ/manageiq-providers-scvmm/pull/7

cc @simaishi

**Comment by djberg96** [comment]
@bronaghs @simaishi Yes, it will require a separate PR because Euwe uses the old PS script. This would require backporting powershell.rb as well, at a minimum.

**Comment by djberg96** [comment]
@simaishi Do you want me to add a "euwe/yes" label even though it requires a separate PR? (Which I've submitted at https://github.com/ManageIQ/manageiq/pull/15362)

**Comment by simaishi** [comment]
@djberg96 In case of needing a separate PR for different branch, it would help if you can add the yes label as well as the branch specific PR link (or a comment that you'll create a separate PR).

Since the `euwe/yes` label doesn't exist here, your comment would be good enough. Thanks for letting me know!

**Comment by simaishi** [comment]
Fine backport (to manageiq repo) details:

```
$ git log -1
commit 6bbdd7817ff5c69b9fe906c1e0c7df872313133d
Author: Bronagh Sorota <bsorota@redhat.com>
Date:   Tue Jun 6 16:59:55 2017 -0400

    Merge pull request #2 from djberg96/storage_fileshares
    
    Add support for storage fileshares
    (cherry picked from commit 7acce0382a8b10db453fe58e068ef97dec8c66a0)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1461169
```

**Pull request merged**
