### PR TITLE
enable vcr cassettes

### PR DESCRIPTION
**Pull request by durandom**

### CODE REVIEW

**Comment by juliancheal** [comment]
LTGM 👍

**Comment by bronaghs** [comment]
@durandom - can you fix the indentation (I know, a nit pick!)

**Comment by durandom** [comment]
Thanks for nitpicking :) Made me look closer and saw there _are_ __no__ vcr specs in here. A dream come true 🎉 

so closing...

**Comment by juliancheal** [comment]
I keep forgetting to see about changing the generator as that's where the wrong indentation starts from.

**Comment by djberg96** [comment]
Well, at the moment the vcr cassette is under spec/tools/scvmm_data in the old repo. Will that be an issue? I don't really care where it lives, but I will have to update the spec file.

**Comment by durandom** [comment]
> Well, at the moment the vcr cassette is under spec/tools/scvmm_data in the old repo. Will that be an issue? I don't really care where it lives, but I will have to update the spec file.

Where is that used? I dont find any `vcr` in the specs...
Looking at https://github.com/ManageIQ/manageiq-providers-scvmm/pull/4

**Pull request closed without merging**
