### PR TITLE
Check connection to VMM when verifying credentials

### PR DESCRIPTION
**Pull request by agrare**
When verifying credentials connect to the VMM service to confirm that
the credentials are privileged enough.

With this now verify fails with:
`Credential validation was not successful: Unable to connect: You cannot contact the VMM management server. The credentials provided have insufficient privileges on DEV-SCVMM2K12\Administrator.`

screenshot from 2018-03-23 12-12-40

https://bugzilla.redhat.com/show_bug.cgi?id=1549667

### CODE REVIEW

**Comment by djberg96** [comment]
I've never been a big fan of having methods return multiple values. Modifying `execute_powershell_json` to return 3 values instead of one just feels clumsy to me. I worry about breakage in general.

Since you want access to the stdout and stderr properties, what about just using `run_powershell_script` instead? Won't that give you everything you need?

**Comment by agrare** [comment]
Hm I do need to check the parsed json results, I guess I can call `parse_json_results(results.stdout)` in the calling method but then it basically becomes `execute_powershell_json`

**Comment by agrare** [comment]
@djberg96 I still need to fix the spec tests but how does that look?

**Comment by djberg96** [comment]
@agrare 👍

**Comment by agrare** [comment]
@djberg96 PTAL, updated specs to work with `run_powershell_script`

**Comment by djberg96** [comment]
The two codeclimate complaints are minor cognitive load complaints. Ignoring for now.

**Comment by simaishi** [comment]
Gaprindashvili backport details:

```
$ git log -1
commit 24c67e02a910cca912e377d5fde98a1369b93de9
Author: Daniel Berger <djberg96@gmail.com>
Date:   Mon Mar 26 13:25:22 2018 -0600

    Merge pull request #66 from agrare/check_connection_to_scvmm_server_on_verification
    
    Check connection to VMM when verifying credentials
    (cherry picked from commit b4bfeb92b560956610e8636c685d9e2c3967cf52)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1560004
```

**Pull request merged**
